source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'pry',        group: :development

gem 'active_model_serializers', '~> 0.10.0'
